### PR TITLE
README - Update to new domain

### PR DESCRIPTION
**Pull request by splintor**
http://thejewsarecoming.tv/

### CODE REVIEW

**Comment by yonatanm** [comment]
Thanks for the help. and a good point.
I prefer the `http://www.thejewsarecoming.tv`

**Comment by splintor** [comment]
> I prefer the http://www.thejewsarecoming.tv

Why?

**Comment by yonatanm** [comment]
as websites, usually have www. as a prefix. but I less care about it. 
if you change it please also change it in the gatsby-config where we set the URL for the site (used for generating absolute links for social etc.

**Comment by splintor** [comment]
> as websites, usually have www. as a prefix.

Not any more. https://dropwww.com/why

Updated `gatsby-config.js` as well.

**Comment by yonatanm** [comment]
I'm ok with that
I think that we need to change the config/.env.production 
I also have GA on www.* site.
I will merge that after I check GA

**Comment by splintor** [comment]
No response from owner... 😢 

Closing.

**Pull request closed without merging**
